### PR TITLE
Fixed enabling of TLS 1.2 to work with older .NET Framework versions - Fixes #76

### LINKED ISSUE #76: `Set-JenkinsTLSSupport` function fails because [Net.SecurityProtocolType] does not support op_addition
`Set-JenkinsTLSSupport` fails with the error: Method invocation failed because [System.Net.SecurityProtocolType] does not contain a method named 'op_Addition'.

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol + [Net.SecurityProtocolType]::Tls12`

could be updated to something like: 

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol.toString() + ', ' + [Net.SecurityProtocolType]::Tls12`

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR fixes #76:
- Fixed enabling of TLS 1.2 to work with older .NET Framework versions.
- Updated tests to meet Pester V4 guidelines.
- Updated license year to 2018.

@SteelCrusaders - can you review for me when you get a chance? :grin:

The tests were updated to Pester V4 using the standard update script. But I manually changed to the new "When" based context wording.

---
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/jenkins/77)

### CODE REVIEW

**Comment by jeffprice6** [comment]
Thanks for the update and the prompt turnaround! I'm working on some Jenkins automation for my organization and it's been great getting to know your code-base. ~Jeff

**Comment by PlagueHO** [comment]
No worries @jeffprice6 - I'm just glad to hear the module is useful :grin: Should have the PR merged on Monday for you. Cheers!

**Comment by PlagueHO** [comment]
@TobeyHung - can you give this one a review for me?

**Comment by SteelCrusaders** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/jenkins/77)*

**Pull request merged**
