### PR TITLE
Changed Get-JenkinsCrumb cmdlet to accept alternate format crumb - Fixes #70

### LINKED ISSUE #70: Crumb Validation
Crumb validation failure for Internal Jenkins 
Get-JenkinsCrumb should also check for 
$Regex = '^.crumb:([A-Z0-9]*)'

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR fixes issue #70 by allowing the alternate format crumb to be accepted:
`.crumb:1234567890`

I also fixed the readme.md file to remove all Markdown rule violations as well as correcting some spelling mistakes.

---
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/jenkins/71)

### CODE REVIEW

**Comment by SteelCrusaders** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[readme.md, line 29 at r1](https://reviewable.io:443/reviews/iag-nz/jenkins/71#-KpvXB-N7s3ovYWD-Xbs:-KpvXB-O_YMBi8SlTSru:b-pwyoiz) ([raw file](https://github.com/iag-nz/jenkins/blob/64c3d5ffc9d62af39cbf352d6bca3087736ab802/readme.md#L29)):*
> ```Markdown
>  - Test-JenkinsJob: Determines if a Jenkins Job exists.
>  - New-JenkinsJob: Create a new Jenkins Job.
>  - Rename-JenkinsJob: Rename an existing Jenkins Job.
> ```

Did this function get removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/jenkins/71)*

**Comment by PlagueHO** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[readme.md, line 29 at r1](https://reviewable.io:443/reviews/iag-nz/jenkins/71#-KpvXB-N7s3ovYWD-Xbs:-KpvYZtif7eG22nlO_t5:b25u2iw) ([raw file](https://github.com/iag-nz/jenkins/blob/64c3d5ffc9d62af39cbf352d6bca3087736ab802/readme.md#L29)):*
<details><summary><i>Previously, SteelCrusaders (Ashley Tok) wrote…</i></summary><blockquote>

Did this function get removed?
</blockquote></details>

Oops. Merge conflict fix failure. Fixed. Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/jenkins/71)*

**Comment by SteelCrusaders** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[readme.md, line 19 at r1](https://reviewable.io:443/reviews/iag-nz/jenkins/71#-KpvZdc4P5vjZMwdrB6R:-KpvZdc4P5vjZMwdrB6S:b-2lfg3a) ([raw file](https://github.com/iag-nz/jenkins/blob/fab1d405330ad09517511035d0cc26a78ad7d96e/readme.md#L19)):*
> ```Markdown
> > If Windows Management Framework 5.0 or above is not available and and the PowerShell Package management module is not available:
> 
> ```text
> ```

Text? accidental leftover from merge conflicts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/jenkins/71)*

**Comment by SteelCrusaders** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/jenkins/71)*

**Pull request merged**
